#!/bin/sh
#
# This is part 2 of the ppp-on script. It will perform the connection
# protocol for the desired connection.
# Modify: jiangyanfeng@gmail.com
#
/usr/sbin/chat -v				\
TIMEOUT	25					\
ABORT	'\nBUSY\r'				\
ABORT	'\nNO ANSWER\r'				\
ABORT	'\nNO CARRIER\r'			\
ABORT	'\nRINGING\r\n\r\nRINGING\r'		\
ABORT	'\nUsername/Password Incorrect\r' 	\
SAY	"Beginning...\n"			\
''	AT					\
''	ATH0					\
SAY	"Dialing up...$TELEPHONE\n"		\
OK	AT+CGDCONT=1,\"ip\",\"$APN\"		\
OK	ATDT$TELEPHONE				\
CONNECT	\c					\
SAY	"Logging...\n"
