#!/bin/sh
# This script will be put into slave root-fs 
# and run slave automaticly for asic

### config network ###
modprobe hiether;
#ifconfig eth0 hw ether 00:10:85:18:40:91
#ifconfig eth0 10.85.184.78 netmask 255.255.254.0
ifconfig lo up
#route add default gw 10.85.184.1
echo 1048576 > /proc/sys/net/core/rmem_default
echo 3145728 > /proc/sys/net/core/rmem_max
echo 1048576 > /proc/sys/net/core/wmem_default
echo 3145728 > /proc/sys/net/core/wmem_max
echo 2000 > /proc/sys/vm/min_free_kbytes
### 60
### 75
### 9
### 7200
#cat /proc/sys/net/ipv4/tcp_fin_timeout
#cat /proc/sys/net/ipv4/tcp_keepalive_intvl
#cat /proc/sys/net/ipv4/tcp_keepalive_probes
#cat /proc/sys/net/ipv4/tcp_keepalive_time
#cat /proc/sys/net/ipv4/tcp_tw_recycle
#cat /proc/sys/net/ipv4/tcp_tw_reuse
#cat /proc/sys/net/ipv4/tcp_window_scaling
#cat /proc/sys/net/ipv4/tcp_sack
#cat /proc/sys/net/ipv4/tcp_max_tw_buckets
#cat /proc/sys/net/ipv4/tcp_timestamps
#cat /proc/sys/net/ipv4/tcp_synack_retries
#cat /proc/sys/net/ipv4/tcp_syn_retries
#cat /proc/sys/net/ipv4/tcp_max_syn_backlog

echo 25 > /proc/sys/net/ipv4/tcp_fin_timeout
echo 5 > /proc/sys/net/ipv4/tcp_keepalive_intvl
echo 4 > /proc/sys/net/ipv4/tcp_keepalive_probes
echo 40 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle
echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
#echo 0 > /proc/sys/net/ipv4/tcp_window_scaling
#echo 0 > /proc/sys/net/ipv4/tcp_sack
#echo 5000 > /proc/sys/net/ipv4/tcp_max_tw_buckets
#echo 1 > /proc/sys/net/ipv4/tcp_timestamps
#echo 5 > /proc/sys/net/ipv4/tcp_synack_retries
#echo 5 > /proc/sys/net/ipv4/tcp_syn_retries
echo 256 > /proc/sys/net/ipv4/tcp_max_syn_backlog

#modprobe nfs
#telnetd&

echo "modprobe mmz."
/usr/sbin/set_channel

### load sdk ###
MPP_KO_PATH=/module/35xxko
cd $MPP_KO_PATH;
./load3515 -i;

echo "************ load hi3515 mpp ok **************"
mount -t cramfs /dev/mtdblock3 /mnt
### load peripheral driver ###
cd /module/extdrv
/bin/get_board_type
#if [ $? = 0 ]
#then
#	insmod cpu_gpio.ko gBoard_type=0
#else
#	insmod cpu_gpio.ko gBoard_type=1
#fi

case $? in
0)	insmod cpu_gpio.ko gBoard_type=0
	;;
1)	insmod cpu_gpio.ko gBoard_type=1
	;;
2)	insmod cpu_gpio.ko gBoard_type=2
	;;
3)	insmod cpu_gpio.ko gBoard_type=3
	;;
4)	insmod cpu_gpio.ko gBoard_type=1
	insmod cvr402_gpio.ko BoardType=2
	;;	
5)	insmod cpu_gpio.ko gBoard_type=5
	;;	
6)	insmod cpu_gpio.ko gBoard_type=6
	;;	
7)	insmod cpu_gpio.ko gBoard_type=7
	;;
8)	insmod cpu_gpio_fp01093.ko gBoard_type=8
	;;
9)	insmod cpu_gpio.ko gBoard_type=9
	;;
10)	insmod cpu_gpio.ko gBoard_type=10
	;;
esac

#insmod cpu_gpio.ko
insmod gpioi2c.ko

/bin/get_board_type
if [ $? = 8 ]
then
	/bin/get_ntsc_pal_1093
else
	/bin/get_ntsc_pal
fi

if [ $? = 0 ]
then
	#NTSC mode
	echo ">> NTSC mode"
	#insmod tw2865.ko norm=1
	#insmod sv2805.ko norm=1
	/bin/get_board_type
	
	case $? in
	3)	insmod sv2806.ko norm=1 norm_board=3
		;;
	5)	insmod sv2806.ko norm=1 norm_board=5
		;;
	6)	insmod sv2806.ko norm=1 norm_board=6
		;;    
	7)	insmod sv2806.ko norm=1 norm_board=7
		;;
	8)	insmod sv2806_fp01093.ko norm=1 norm_board=8
		;;
	9)	insmod sv2806.ko norm=1 norm_board=9
		;;
	10)	insmod sv2806.ko norm=1 norm_board=10
		;;
	*)	insmod tw2864.ko norm=1
		;;
	esac

		
else
	#PAL mode
	echo ">> PAL mode"
	#insmod tw2865.ko norm=2
	#insmod sv2805.ko norm=2
	/bin/get_board_type
	
	case $? in
	3)	insmod sv2806.ko norm=2 norm_board=3
		;;
	5)	insmod sv2806.ko norm=2 norm_board=5
		;;
	6)	insmod sv2806.ko norm=2 norm_board=6
        ;;    
	7)	insmod sv2806.ko norm=2 norm_board=7
		;;
	8)	insmod sv2806_fp01093.ko norm=2 norm_board=8
		;;
	9)	insmod sv2806.ko norm=2 norm_board=9
		;;
	10)	insmod sv2806.ko norm=2 norm_board=10
		;;
	*)	insmod tw2864.ko norm=2
		;;
	esac	

fi
#insmod rtc_ds1339.ko
#for our hi3515 board

/bin/get_board_type
if [ $? = 9 ]
then
	insmod bq32k.ko
else
	insmod isl1208.ko
fi

insmod hiwdt.ko
insmod hi_ir.ko
/bin/get_board_type

case $? in
0)	echo ">> FP00883"
    /bin/get_fpga_state
    if [ $? = 1 ]
	then
		echo " with FPGA"
		insmod keypad_gpio.ko
	else
		echo " without FPGA"
		/bin/get_keypad_type
		if [ $? = 3 ]
		then
			echo " ROW = 3"
			insmod keypad_no_fpga.ko Row=3
		else
			echo " ROW = 5"
			insmod keypad_no_fpga.ko 
		fi	
	fi
	;;
1)	echo ">> FP00917"
	insmod keypad_cvr402.ko
	;;
2)	echo ">> FP00947A"
	/bin/get_fpga_state
	if [ $? = 1 ]
	then
		echo " with FPGA"
			insmod keypad_gpio.ko
	else
		echo " without FPGA"
		/bin/get_keypad_type
		if [ $? = 3 ]
		then
			echo " ROW = 3"
			insmod keypad_no_fpga.ko Row=3
		else
			echo " ROW = 5"
			insmod keypad_no_fpga.ko 
		fi	
	fi
	;;
3)	echo ">> FP00947AP2"
	/bin/get_fpga_state
	if [ $? = 1 ]
	then
		echo " with FPGA"
			insmod keypad_gpio.ko
	else
		echo " without FPGA"
		/bin/get_keypad_type
		if [ $? = 3 ]
		then
			echo " ROW = 3"
			insmod keypad_no_fpga.ko Row=3
		else
			echo " ROW = 5"
			insmod keypad_no_fpga.ko 
		fi	
	fi
	;;
4)	echo ">> FP00953"
	insmod keypad_cvr402.ko
	;;
5)	echo ">> FP00883P2"
	/bin/get_fpga_state
	if [ $? = 1 ]
	then
		echo " with FPGA"
			insmod keypad_gpio.ko
	else
		echo " without FPGA"
		/bin/get_keypad_type
		if [ $? = 3 ]
		then
			echo " ROW = 3"
			insmod keypad_no_fpga.ko Row=3
		else
			echo " ROW = 5"
			insmod keypad_no_fpga.ko
		fi
	fi
	;;
6)      echo ">> FP00862"
        /bin/get_fpga_state
        if [ $? = 1 ]
        then
                echo " with FPGA"
                        insmod keypad_gpio.ko
        else
                echo " without FPGA"
                /bin/get_keypad_type
                if [ $? = 3 ]
                then
                        echo " ROW = 3"
                        insmod keypad_no_fpga.ko Row=3
                else
                        echo " ROW = 5"
                        insmod keypad_no_fpga.ko
                fi
        fi
        ;;
7)      echo ">> FP00947B"
        /bin/get_fpga_state
        if [ $? = 1 ]
        then
                echo " with FPGA"
                        insmod keypad_gpio.ko
        else
                echo " without FPGA"
                /bin/get_keypad_type
                if [ $? = 3 ]
                then
                        echo " ROW = 3"
                        insmod keypad_no_fpga.ko Row=3
                else
                        echo " ROW = 5"
                        insmod keypad_no_fpga.ko
                fi
        fi
        ;;
8)	echo ">> FP01093"
    /bin/get_fpga_state
    if [ $? = 1 ]
	then
		echo " with FPGA"
		insmod keypad_gpio_fp01093.ko
	else
		echo " without FPGA"
		/bin/get_keypad_type
		if [ $? = 3 ]
		then
			echo " ROW = 3"
			insmod keypad_no_fpga_fp01093.ko Row=3
		else
			echo " ROW = 5"
			insmod keypad_no_fpga_fp01093.ko 
		fi	
	fi
	;;
9)  echo ">> FP01126"
    /bin/get_fpga_state
    if [ $? = 1 ]
    then
        echo " with FPGA"
        insmod keypad_gpio.ko
    else
        echo " without FPGA"
        /bin/get_keypad_type
        if [ $? = 3 ]
        then
            echo " ROW = 3"
            insmod keypad_no_fpga.ko Row=3
        else
            echo " ROW = 5"
            insmod keypad_no_fpga.ko
        fi
    fi
    ;;
10) echo ">> FP01140"
    /bin/get_fpga_state
    if [ $? = 1 ]
    then
        echo " with FPGA"
        insmod keypad_gpio.ko
    else
        echo " without FPGA"
        /bin/get_keypad_type
        if [ $? = 3 ]
        then
            echo " ROW = 3"
            insmod keypad_no_fpga_fp01140.ko Row=3
        else
            echo " ROW = 5"
            insmod keypad_no_fpga.ko
        fi
    fi
    ;;
	
esac



#if [ $? = 0 ]
#then
#	echo ">> FP00883V2"
#	/bin/get_fpga_state
#	if [ $? = 1 ]
#	then
#		echo " with FPGA"
#		insmod keypad_gpio.ko
#	else
#		echo " without FPGA"
#		insmod keypad_no_fpga.ko
#	fi
#else
#	echo ">> FP00917V1"
#	insmod keypad_cvr402.ko
#	insmod cvr402_gpio.ko

#fi

/bin/get_board_type
if [ $? = 8 ]
then
	insmod sensor_gpio_fp01093.ko
else
	insmod sensor_gpio.ko
fi

#insmod at88sc_drv.ko
#insmod 74hc165.ko

### load disk and input driver
#modprobe usbhid
modprobe evdev
modprobe mousedev

#insmod /lib/modules/2.6.24-rt1-hi3515v100/kernel/drivers/input/usbtouchscreen.ko
#modprobe vfat
#modprobe scsi_mod
modprobe sd_mod
#modprobe nls_base
insmod /lib/modules/2.6.24-rt1-hi3515v100/kernel/fs/nls/nls_iso8859-1.ko
insmod /lib/modules/2.6.24-rt1-hi3515v100/kernel/fs/nls/nls_cp437.ko
insmod /lib/modules/2.6.24-rt1-hi3515v100/kernel/fs/nls/nls_ascii.ko
#insmod nls_iso8859-1.ko
#insmod nls_cp437.ko
#insmod nls_ascii.ko
#modprobe nls_iso8859-2
modprobe usb-storage

#modprobe nls_base
#modprobe nls_cp437
modprobe fat
modprobe vfat
modprobe msdos

#modprobe nls_iso8859-1
#modprobe nls_ascii
#modprobe scsi_mod
modprobe sd_mod
modprobe sr_mod
modprobe sg
#modprobe libata

modprobe ext2
modprobe cdrom

insmod hidmac.ko
modprobe ahci

insmod /lib/modules/2.6.24-rt1-hi3515v100/kernel/net/packet/af_packet.ko

#config duplicate pin
himm 0x200f00b4 0x1

mount -t usbfs none /proc/bus/input

#log path fsck
cd /etc/init.d
./fsck.sh

#keep probe network
cd /etc/init.d
#./ping.sh&

#mount application and run 
#mount -t cramfs /dev/mtdblock2 /mnt
export LD_LIBRARY_PATH=/mnt:$LD_LIBRARY_PATH
cd /mnt
./fafd &
./hi_dvr &

